event/urls.py
from django.conf.urls import url

from . import views

app_name = 'event'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^new_event$', views.new_event, name='new_event'),
    url(r'^(?P<event_id>[0-9]+)/$', views.event_detail, name='event_detail'),
    #url(r'^(?P<event_id>[0-9]+)/(?P<person_id>[0-9]+)$', views.delete_name, name='del_name'),
    url(r'^(?P<event_id>[0-9]+)/delete$', views.delete_name, name='del'),
    url(r'^delete$', views.delete_event, name='del_event'),
    url(r'^adminhome$', views.admin_home, name='homeadmin'),
    url(r'^about$', views.about, name='about'),
    url(r'^login$', views.login, name='login'),
    url(r'^login_page$', views.login_page, name='login_page'),
    url(r'^logout$', views.logout, name='logout'),
]

superevent/urls.py
from django.conf.urls import include, url

from event import views
from django.contrib import admin

urlpatterns = [
    url(r'^', include('event.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

event/models.py
from django.db import models
#from django.utils import timezone

class Event(models.Model):
    event_name = models.TextField(default='') #name
    event_detail = models.TextField(default='') #detail
    event_numset = models.IntegerField(default=0) #limit for start
    event_location = models.TextField(default='') #location
    pcount = models.IntegerField(default=0) #person count
    #date = models.DateTimeField(default=timezone.now())#'date published')YYYY-MM-DD HH:MM

class Person(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE, default=1)
    fname = models.TextField(default='') #first name
    lname = models.TextField(default='') #last name

event/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
#from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required

from .models import Event , Person

# Create your views here.
def home(request):
    event_list = Event.objects.order_by('event_name')
    context = {'event_list': event_list}
    return render(request, 'home.html', context)


def new_event(request):
    event = Event.objects.all()
    if request.method == 'POST':
        if request.POST['name'] == "":
            return render(request, 'create_event.html', {'event': event, 'error_msg':"Please input Event Name"},)
        else:
            Event.objects.create(event_name=request.POST['name'], event_detail=request.POST['detail'],
                event_numset=request.POST['numset'], event_location=request.POST['location'], pcount=0,)
        return HttpResponseRedirect(reverse('event:home',))

    
    return render(request, 'create_event.html', {'event': event},)


def event_detail(request, event_id):
    event = get_object_or_404(Event, pk=event_id)
    if request.method == 'POST':
        event.person_set.create(fname=request.POST['firstname'], lname=request.POST['lastname'])
        event.pcount += 1
        event.save()
        return HttpResponseRedirect(reverse('event:event_detail',args=(event.id,)))
        
    return render(request, 'detail.html', {'event':event},)

def sign_name(request, event_id):
    pass
    #return HttpResponseRedirect(reverse('event_detail',kwargs={'event_id':event_id}))
        #return HttpResponseRedirect(reverse('event:event_detail',args=(event.id,)))

def delete_name(request, event_id):    #, person_id
    event = get_object_or_404(Event, pk=event_id)
    person_name = event.person_set.get(pk=request.POST['del_btn'])#request.POST['del_btn']
    person_name.delete()
    event.pcount -= 1
    event.save()
    return HttpResponseRedirect(reverse('event:event_detail',args=(event.id,)))

def delete_event(request):
    password = "delete"
    if request.method == 'POST':
        event = get_object_or_404(Event, pk=request.POST['numdel'])
        #id_event = Event.objects.get(pk=request.POST['numdel'])
    
        #check_event_id = Event.objects.filter(id=event)
        pw = request.POST['pw']
        if (pw == password) :
            event.delete()

        else:
            pass
    return HttpResponseRedirect(reverse('event:homeadmin',))

    '''password = "delete"
    if request.method == 'POST':
        #event = get_object_or_404(Event, pk=request.POST['numdel'])
        id_event = Event.objects.get(pk=request.POST['numdel'])
    
        check_event_id = Event.objects.filter(id=id_event)
        pw = request.POST['pw']
        if check_event_id and (pw == password) :
            event.delete()

        else:
            pass
    return HttpResponseRedirect(reverse('event:home',))'''


    '''event = get_object_or_404(Event, pk=request.POST['numdel'])
    password = "delete"
    if request.method == 'POST':
        pw = request.POST['pw']
        if pw == password:
            try:
                event.delete()
            except:
                pass
        else:
            pass
    return HttpResponseRedirect(reverse('event:home',))'''
def login_page(request):
    return render(request, 'login.html')



def login(request):    
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is not None:
        login(request, user)
        #return HttpResponseRedirect(reverse('event:homeadmin',))
        #return HttpResponseRedirect('/adminhome')
        return HttpResponseRedirect('/adminhome')
    else:
        return HttpResponseRedirect('/login')


def logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('event:login',))



@login_required(login_url='event:login_page')
def admin_home(request):
    event_list = Event.objects.order_by('event_name')
    context = {'event_list': event_list}
    return render(request, 'homeadmin.html', context)

def about(request):
    return render(request, 'about.html')

event/templates/about.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'event/detailbg.css' %}" />

<link rel="stylesheet" type="text/css" href="{% static 'event/navbar.css' %}" />

<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
<title>About</title>
</head>

<ul>
  <li><a href="/">Home</a></li>
  <!--<li style="float:right"><a href="adminhome">VIP</a>-->
  <li style="float:right"><a href="about">About</a>
</ul>

<body>
<h1>About Event Application</h1>
This app built for someone need to create event or finding event. It's will make you decide <br>
แอพนี้สร้างเพื่อให้คนที่สนใจจะจัดงาน event หรือหางาน event ใหม่ๆที่ไม่เป็นที่รู้จักได้ทำการตัดสินใจง่ายขึ้น

<h2>App feature</h2>
- create event<br>
- sign name interested event<br>
- count number people sign name
</body>
</html>

event/templates/create_event.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'event/detailbg.css' %}" />

<link rel="stylesheet" type="text/css" href="{% static 'event/navbar.css' %}" />

<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <title>Event Detail</title>

</head>
    <body>

    <ul>
  <li><a href="/"><< Home</a></li>
  <li><a href="new_event">Start new Event</a></li>
  <li style="float:right"><a href="about">About</a>
</ul>

        <h1 style="text-align: center">Create</h1>

        <form action="{% url 'event:new_event' %}" method="POST">
            <div class="container">
            {% if error_msg %}
            <div class="alert alert-danger" role="alert">
                <strong>{{ error_msg }}</strong>
            </div>
            {% endif %}
            <div class="input-group input-group-lg"> 
                <span class="input-group-addon" id="sizing-addon1">Event Name</span>
                <input type="text" class="form-control" name="name" id="id_name" placeholder="Event name" aria-describedby="sizing-addon1">
            </div>

            <div class="input-group input-group-lg">
                <span class="input-group-addon" id="sizing-addon1">Location</span>
                <textarea type="text" class="form-control" name="detail" id="id_detail" placeholder="Event detail" cols="40" rows="5" style="width:1000px; height:200px;" Event Location" aria-describedby="sizing-addon1"/></textarea>
            </div>
            
            <div class="input-group input-group-lg">
                <span class="input-group-addon" id="sizing-addon1">Location</span>
                <input type="text" class="form-control" name="location" id="id_location" placeholder="Event Location" aria-describedby="sizing-addon1">
            </div>
            <div class="input-group input-group-lg">
                <span class="input-group-addon" id="sizing-addon1">Limit for start</span>
                <input type="number" class="form-control" type="number" name="numset" id="id_numset" value="0" aria-describedby="sizing-addon1">
            </div>
            
            <br><input type="submit" value="Submit" id="id_submit" />
            {% csrf_token %}
            </br><a href="/">Not now.
            </div>
        </form>
    </body>
</html>

event/templates/detail.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'event/detailbg.css' %}" />

<link rel="stylesheet" type="text/css" href="{% static 'event/navbar.css' %}" />

<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <title>Event Detail</title>

</head>

<style>
.button {
    background-color: #4CAF50; /* Green */
    border: none;
    color: white;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
}
.buttonRed {
    background-color: white;
    color: red;
    
}
.buttonRed:hover {
    background-color: #b30000;
    color: white;
}

.buttonBlack {
    background-color: white;
    color: black;
    border: 2px solid #555555;
}
.buttonBlack:hover {
    background-color: #555555;
    color: white;
}

.boxBlue {
	display: inline-block;
    margin: 4px 2px;
    padding: 40px 40px;
    border: dotted #0000ff;
    background-color: rgba(77, 210, 255, 0.5);
      
}

.boxYellow {
	display: inline-block;
    margin: 4px 2px;
    padding: 40px 40px;
    border: dotted #0000ff;
    background-color: rgba(255, 255, 153, 0.5);
      
}

input[type=text] {
    padding: 12px 20px;
    margin: 8px 0;
    box-sizing: border-box;
    border: none;
    background-color: rgba(230, 255, 255, 0.5);
    color: black;
}
strong{color: rgb(0, 0, 153);}

</style>

<ul>
  <li><a href="/"><< Home</a></li>
  <li style="float:right"><a href="../about">About</a>
</ul>

    <body>

    <div class="container">

    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="text-center">

            <h1>{{event.event_name}}</h1>
         
            </div>
        </div>
    </div>
   

    
    <div class="row">
    <div class="col-md-6 col-md-offset-3">    

    <div class="boxBlue" >
    <font size="5">
        <strong>Detail :</strong> {{event.event_detail}}<br>
        <strong>Location :</strong> {{event.event_location}}<br>
        <strong>Start at :</strong> {{event.event_numset}} person<br>
        <strong>Total register :</strong> {{event.pcount}}
        </font>
      
        </div>
         </div>
         
        </div>
  <div class="row">
    <div class="col-md-6 col-md-offset-3"> 
        
        <h3>Person register list</h3>
        <table class="table table-hover">

        {% if event.person_set.all %}
            {% for person in event.person_set.all %}
            <tr>

                <form action="{% url 'event:del' event.id %}" method="POST">
                {% csrf_token %}
                
                <td>{{ forloop.counter }}: {{ person.fname }} - {{ person.lname }}</td>
                <td><button class="button buttonRed" type="submit" name="del_btn" value="{{ person.id }}">Delete {{ forloop.counter }}</button></a></td>

                </br>
                </form>
            </tr>
            {% endfor %}           
        {% else %}
            <p>No anyone register</p>
        {% endif %}
        </td></tr>
       </table>
         </div>
         </div>
         </div>
    
        <h2 style="display:block; padding:20px " >Register</h2>
        <form action="{% url 'event:event_detail' event.id %}" method="POST" style="display:block; padding:20px ">
            {% csrf_token %}
            <font size="3">
            First Name : <input type="text" name="firstname" id="id_firstname" placeholder="Your first name" /> -   
            Last Name : <input type="text" name="lastname" id="id_lastname" placeholder="Your last name" /></br>
            </font>
            <input class="btn btn-success" type="submit" value="Submit" id="id_submit" />
        </form>
  <div class="container">

    <div class="row">
        <div class="col-md-6 col-md-offset-3">
        </div>
</div>
</div>
<div style="display:block; padding:20px">
<a type="button" class="btn btn-primary" href="/" style="float: left;">Home</a>
</div>
    

    </body>
</html>

event/templates/home.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'event/homebg.css' %}" />

<link rel="stylesheet" type="text/css" href="{% static 'event/tablehyperlink.css' %}" />

<link rel="stylesheet" type="text/css" href="{% static 'event/navbar.css' %}" />



<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
        <title>Event Start</title>
</head>


<style>
table {
    border-collapse: collapse;
}

table, td, th {
    border: 1px solid black;
    text-align: center;
}

h1 {
  background-color: rgba(255, 255, 0, 0.5);
  color: black;
}


.button {
    background-color: #4CAF50; /* Green */
    border: none;
    color: white;
    padding: 15px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
}
.buttonBlack {
    background-color: white;
    color: black;
    border: 2px solid #555555;
}
.buttonBlack:hover {
    background-color: #555555;
    color: white;
}
/* unvisited link */
a:link {
    color: blue;
}

/* visited link */
a:visited {
    color: black;
}

/* mouse over link */
a:hover {
    color: red;
}

/* selected link */
a:active {
    color: green;
}

</style>

<ul>
  <li><a href="">Home</a></li>
  <li><a href="new_event">Start new Event</a></li>
  <li style="float:right"><a href="adminhome">VIP</a>
  <li style="float:right"><a href="about">About</a>
</ul>

    
    <body>
            <div class="container">
            <div class="text-center">
            

            <h1>Event</h1>
            </div>
            </div>
    
      

        <div style="text-align:center">  
        <a class="button buttonBlack" href="new_event">Start new Event</a>
        </div>
        <br>
        <br>
        



        <table class="table table-inverse table-hover">
  <thead class="alert alert-info">
  {% if event_list %}
    <tr>
      <th>#</th>
      <th>Event</th>
      <th>Count / at least</th>
    </tr>
  </thead>
  <tbody>

  {% for event in event_list %}
    <tr class='alert alert-success'>
    
    
      <td scope="row">{{ forloop.counter }}</td>
      <td><a href="{{ event.id }}/">{{ event.event_name }}</a></td>
      <td>{{ event.pcount }} / {{ event.event_numset }}</td>
    </tr>
    {% endfor %}

    {% else %}
    
    <div class="alert alert-danger" role="alert">
  <strong>Sorry no event!</strong>
  <a href="new_event" class="alert-link">Create new here</a>.
</div>
    
    {% endif %}
  </tbody>
</table>
<!--
        <form action="{% url 'event:del_event' %}" method="POST">
        Delete Event by ID <br>
        <input type="password" name="pw" id="id_pw"/>Password
        <input type="number" name="numdel" id="id_numdel"/>ID
        <input type="submit" value="Submit" id="id_submit" />
        {% csrf_token %}
        </form>-->
    </body>
</html> 

event/templates/home2.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'event/homebg.css' %}" />


<html>
<style>
table {
    border-collapse: collapse;
}

table, td, th {
    border: 1px solid black;
}

.button {
    background-color: #4CAF50; /* Green */
    border: none;
    color: white;
    padding: 15px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
}
.buttonBlack {
    background-color: white;
    color: black;
    border: 2px solid #555555;
}
.buttonBlack:hover {
    background-color: #555555;
    color: white;
}
/* unvisited link */
a:link {
    color: blue;
}

/* visited link */
a:visited {
    color: black;
}

/* mouse over link */
a:hover {
    color: red;
}

/* selected link */
a:active {
    color: green;
}

</style>

    <head>
        <title>Event Start</title>
    </head>
    <body>
        
        <h1 style= "text-align:center;">Event</h1>
        
        
        <div style="text-align:center">  
        <a class="button buttonBlack" href="new_event">Start new Event</a>
        </div>
        <br>
        <br>
        



        <table class="table table-hover">
  <thead>
  {% if event_list %}
    <tr>
      <th>Event ID</th>
      <th>Event</th>
      <th>Count / at least</th>
    </tr>
  </thead>
  <tbody>
    <tr>
    
    {% for event in event_list %}
      <th scope="row">{{ event.id }}</th>
      <td><a href="{{ event.id }}/">{{ event.event_name }}</a></td>
      <td>{{ event.pcount }} / {{ event.event_numset }}</td>
    </tr>
    {% endfor %}

    {% else %}
    
    <div class="alert alert-danger" role="alert">
  <strong>Sorry no event!</strong>
  <a href="new_event" class="alert-link">Create new here</a>.
</div>
    
    {% endif %}
  </tbody>
</table>

        <form action="{% url 'event:del_event' %}" method="POST">
        Delete Event by ID <br>
        <input type="password" name="pw" id="id_pw"/>Password
        <input type="number" name="numdel" id="id_numdel"/>ID
        <input type="submit" value="Submit" id="id_submit" />
        {% csrf_token %}
        </form>
    </body>
</html> 

event/templates/homeadmin.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'event/homebg.css' %}" />

<link rel="stylesheet" type="text/css" href="{% static 'event/tablehyperlink.css' %}" />



<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
</head>


<style>
table {
    border-collapse: collapse;
}

table, td, th {
    border: 1px solid black;
    text-align: center;
}

h1 {
  background-color: rgba(255, 255, 0, 0.5);
  color: black;
}


.button {
    background-color: #4CAF50; /* Green */
    border: none;
    color: white;
    padding: 15px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
}
.buttonBlack {
    background-color: white;
    color: black;
    border: 2px solid #555555;
}
.buttonBlack:hover {
    background-color: #555555;
    color: white;
}
/* unvisited link */
a:link {
    color: blue;
}

/* visited link */
a:visited {
    color: black;
}

/* mouse over link */
a:hover {
    color: red;
}

/* selected link */
a:active {
    color: green;
}

</style>

    <head>
        <title>Event Start</title>
    </head>
    <body>

            <div class="text-center">

            <h1>Event</h1>
         
            </div>
      





        
        
        
        
        <div style="text-align:center">  
        <a class="button buttonBlack" href="new_event">Start new Event</a>
        </div>
        <br>
        <br>
        



        <table class="table table-inverse table-hover">
  <thead class="alert alert-info">
  {% if event_list %}
    <tr>
      <th>Event ID</th>
      <th>Event</th>
      <th>Count / at least</th>
    </tr>
  </thead>
  <tbody>

  {% for event in event_list %}
    <tr class='alert alert-success'>
    
    
      <td scope="row">{{ event.id }}</td>
      <td><a href="{{ event.id }}/">{{ event.event_name }}</a></td>
      <td>{{ event.pcount }} / {{ event.event_numset }}</td>
    </tr>
    {% endfor %}

    {% else %}
    
    <div class="alert alert-danger" role="alert">
  <strong>Sorry no event!</strong>
  <a href="new_event" class="alert-link">Create new here</a>.
</div>
    
    {% endif %}
  </tbody>
</table>

        <form action="{% url 'event:del_event' %}" method="POST">
        Delete Event by ID <br>
        <input type="password" name="pw" id="id_pw"/>Password
        <input type="number" name="numdel" id="id_numdel"/>ID
        <input type="submit" value="Submit" id="id_submit" />
        {% csrf_token %}
        </form>

        <a type="button" class="btn btn-primary" href="/">User Home</a>

        <a href="{% url 'event:logout' %}">logout</a>
    </body>
</html> 

event/templates/homebackup.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'event/homebg.css' %}" />

<link rel="stylesheet" type="text/css" href="{% static 'event/navi.css' %}" />

<html>
<style>
table {
    border-collapse: collapse;
}

table, td, th {
    border: 1px solid black;
}

.button {
    background-color: #4CAF50; /* Green */
    border: none;
    color: white;
    padding: 15px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
}
.buttonBlack {
    background-color: white;
    color: black;
    border: 2px solid #555555;
}
.buttonBlack:hover {
    background-color: #555555;
    color: white;
}
/* unvisited link */
a:link {
    color: blue;
}

/* visited link */
a:visited {
    color: black;
}

/* mouse over link */
a:hover {
    color: red;
}

/* selected link */
a:active {
    color: green;
}

#banner {
  
  margin: 0 auto;
  padding: 0;
  background-color: rgba(128, 223, 255, 0.3);
}

#banner h1 {
  margin: 0;
  padding: 25px;
  color: #800033;
}

</style>

    <head>
        <title>Event Start</title>
    </head>
    <body>
        <div id="banner">
        <h1 style= "text-align:center;">Event</h1>
        </div>
        <br>
        <div style="text-align:center">  
        <a class="button buttonBlack" href="new_event">Start new Event</a>
        </div>
        <br>
        <br>
        <table style="text-align:center;" align="center">
        <tr>
    <th bgcolor="#ccff66">Event ID</th>
    <th bgcolor="#ccff66">Event</th>
    <th bgcolor="#ccff66">Count</th>
  </tr>
        {% if event_list %}
            
                {% for event in event_list %}
                <tr>
                    <td bgcolor="#ffffcc"> {{ event.id }} </td>
                    <td bgcolor="#ffffcc"><a href="{{ event.id }}/">{{ event.event_name }}</a></td> <td bgcolor="#ffffcc">{{ event.pcount }} / {{ event.event_numset }}</td>
                </tr>
                {% endfor %}
            
        {% else %}
        <tr><td bgcolor="#ffffcc">
            <p>Sorry no event</p>
            </td></tr>
        {% endif %}
        </table>

        <form action="{% url 'event:del_event' %}" method="POST">
        Delete Event by ID <br>
        <input type="password" name="pw" id="id_pw"/>Password
        <input type="number" name="numdel" id="id_numdel"/>ID
        <input type="submit" value="Submit" id="id_submit" />
        {% csrf_token %}
        </form>
    </body>
</html>        

event/templates/login.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'event/navbar.css' %}" />


<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">



<ul>
  <li><a href="/"><< Home</a></li>
  <li style="float:right"><a href="about">About</a>
</ul>




<h1>Hello {{ user }}</h1>


{% if request.user.is_authenticated %}
<a href="{% url 'event:logout' %}">logout</a>
{% else %}
<form action="{% url 'event:login' %}" method="POST">
{% csrf_token %}
	USERNAME :<BR>
	<input type="text" name="username"><BR>
	PASSWORD :<BR>
	<input type="password" name="password"><BR>
	<input type="submit">
</form>
{% endif %}